 Derived from
 
 https://www.axonlab.org/hcph-sops/data-management/edf-to-bids/
 
 https://github.com/TheAxonLab/hcph-sops/blob/mkdocs/code/eyetracking/convert.py

Make sure the python version >=3.7 to support the statement

In [4]:
from __future__ import annotations 
from pathlib import Path
import pandas as pd
import numpy as np
from pyedfread import read_edf
from collections import defaultdict
from itertools import product, groupby
from warnings import warn
import re

In [5]:
# Global variable from 
# https://github.com/TheAxonLab/hcph-sops/blob/mkdocs/code/eyetracking/convert.py

# If setting WRITE_RAW_EDF as True, no preprocessing will be conducted on the edf data
WRITE_RAW_EDF = True
# -------------------------------------------------------------------------------
DEFAULT_EYE = "right"
DEFAULT_FREQUENCY = 1000 #It is 1000
DEFAULT_MODE = "P-CR"
DEFAULT_SCREEN = (0, 800, 0, 600)

# EyeLink calibration coordinates from
# https://www.sr-research.com/calibration-coordinate-calculator/
# Affect the performance?
EYELINK_CALIBRATION_COORDINATES = [
    (400, 300),
    (400, 51),
    (400, 549),
    (48, 300),
    (752, 300),
    (48, 51),
    (752, 51),
    (48, 549),
    (752, 549),
    (224, 176),
    (576, 176),
    (224, 424),
    (576, 424),
]

EYE_CODE_MAP = defaultdict(lambda: "unknown", {"R": "right", "L": "left", "RL": "both"})
EDF2BIDS_COLUMNS = {
    "g": '',
    "p": "pupil",
    "h": "href",
    "r": "raw",
    "fg": "fast",
    "fh": "fast_href",
    "fr": "fast_raw",
}

BIDS_COLUMNS_ORDER = (
    [f"eye{num}_{c}_coordinate" for num, c in product((1, 2), ("x", "y"))]
    + [f"eye{num}_pupil_size" for num in (1, 2)]
    + [f"eye{num}_pupil_{c}_coordinate" for num, c in product((1, 2), ("x", "y"))]
    + [f"eye{num}_fixation" for num in (1, 2)]
    + [f"eye{num}_saccade" for num in (1, 2)]
    + [f"eye{num}_blink" for num in (1, 2)]
    + [f"eye{num}_href_{c}_coordinate" for num, c in product((1, 2), ("x", "y"))]
    + [f"eye{num}_{c}_velocity" for num, c in product((1, 2), ("x", "y"))]
    + [f"eye{num}_href_{c}_velocity" for num, c in product((1, 2), ("x", "y"))]
    + [f"eye{num}_raw_{c}_velocity" for num, c in product((1, 2), ("x", "y"))]
    + [f"fast_{c}_velocity" for c in ("x", "y")]
    + [f"fast_{kind}_{c}_velocity" for kind, c in product(("href", "raw"), ("x", "y"))]
    + [f"screen_ppdeg_{c}_coordinate" for c in ("x", "y")]
    + ["timestamp"]
)

Read in the edf file

In [6]:
subject_idx = 2
T_idx = 1

DATA_PATH = Path(f"/home/debi/jaime/repos/MR-EyeTrack/data/study/sub-{subject_idx:03d}/et")

# Find the .edf file automatically
edf_files = list(DATA_PATH.glob(f"*T{T_idx}*.EDF"))
if not edf_files:
    edf_files = list(DATA_PATH.glob("*.EDF"))
    
if edf_files:
    edf_name = edf_files[0].name
    print(f"Found EDF file: {edf_name}")
else:
    raise FileNotFoundError(f"No EDF file found in {DATA_PATH}")

file_path = str(DATA_PATH / edf_name)
print(file_path)
ori_recording, ori_events, ori_messages = read_edf(file_path)
# The first timestamp of  `recording`
print(f" {ori_recording[100000:100100]}")
# print(ori_messages)
# print(ori_events)
# print(messages)
ori_messages = ori_messages.rename(
    columns={
        # Normalize weird header names generated by pyedfread
        "message": "trialid",
        "trial": "trial",
        # Convert some BIDS columns
        "time": "timestamp",
    }
)

recording = ori_recording
messages = ori_messages
events = ori_events
print(f'\nThe entire info of `message`: \n{messages[20:80]}')
recording.columns

Found EDF file: 002_mreyetrack_4points_2025-12-19_17h34.06.389.EDF
/home/debi/jaime/repos/MR-EyeTrack/data/study/sub-002/et/002_mreyetrack_4points_2025-12-19_17h34.06.389.EDF
loadEvents = 1
              time  px_left  px_right  py_left  py_right  hx_left  hx_right  \
100000  5415568.0 -32768.0   -1040.0 -32768.0   -6202.0 -32768.0     -81.0
100001  5415569.0 -32768.0   -1034.0 -32768.0   -6210.0 -32768.0     -77.0
100002  5415570.0 -32768.0   -1026.0 -32768.0   -6210.0 -32768.0     -71.0
100003  5415571.0 -32768.0   -1018.0 -32768.0   -6204.0 -32768.0     -64.0
100004  5415572.0 -32768.0   -1022.0 -32768.0   -6196.0 -32768.0     -67.0
...           ...      ...       ...      ...       ...      ...       ...
100095  5415663.0 -32768.0   -1234.0 -32768.0   -6249.0 -32768.0    -240.0
100096  5415664.0 -32768.0   -1238.0 -32768.0   -6248.0 -32768.0    -243.0
100097  5415665.0 -32768.0   -1240.0 -32768.0   -6248.0 -32768.0    -244.0
100098  5415666.0 -32768.0   -1237.0 -32768.0   -6248.0 -32768.0    -242.0
100099  5415667.0 -32768.0   -1232.0 -32768.0   -6254.0 -32768.0    -238.0

        hy_left  hy_right  pa_left  ...  fgyvel  fhxvel  fhyvel        frxvel  \
100000 -32768.0   -1006.0 -32768.0  ...     NaN     0.0     0.0  4.591354e-41
100001 -32768.0   -1013.0 -32768.0  ...     NaN     0.0     0.0  4.591354e-41
100002 -32768.0   -1013.0 -32768.0  ...     NaN     0.0     0.0  4.591354e-41
100003 -32768.0   -1007.0 -32768.0  ...     NaN     0.0     0.0  4.591354e-41
100004 -32768.0   -1000.0 -32768.0  ...     NaN     0.0     0.0  4.591354e-41
...         ...       ...      ...  ...     ...     ...     ...           ...
100095 -32768.0   -1057.0 -32768.0  ...     NaN     0.0     0.0  4.591354e-41
100096 -32768.0   -1057.0 -32768.0  ...     NaN     0.0     0.0  4.591354e-41
100097 -32768.0   -1057.0 -32768.0  ...     NaN     0.0     0.0  4.591354e-41
100098 -32768.0   -1057.0 -32768.0  ...     NaN     0.0     0.0  4.591354e-41
100099 -32768.0   -1062.0 -32768.0  ...     NaN     0.0     0.0  4.591354e-41

              fryvel    flags    input  buttons    htype  errors
100000  4.162697e-41  32641.0  32768.0      0.0 -32768.0     0.0
100001  4.162697e-41  24449.0  32768.0      0.0 -32768.0     0.0
100002  4.162697e-41  24449.0  32768.0      0.0 -32768.0     0.0
100003  4.162697e-41  24449.0  32768.0      0.0 -32768.0     0.0
100004  4.162697e-41  24449.0  32768.0      0.0 -32768.0     0.0
...              ...      ...      ...      ...      ...     ...
100095  4.162697e-41  24449.0  32768.0      0.0 -32768.0     0.0
100096  4.162697e-41  24449.0  32768.0      0.0 -32768.0     0.0
100097  4.162697e-41  24449.0  32768.0      0.0 -32768.0     0.0
100098  4.162697e-41  24449.0  32768.0      0.0 -32768.0     0.0
100099  4.162697e-41  24449.0  32768.0      0.0 -32768.0     0.0

[100 rows x 40 columns]

The entire info of `message`:
    timestamp  trial                                            trialid
20    4752964     -1                  !CAL Slip rotation correction OFF
21    4752965     -1                !CAL CALIBRATION HV5 R RIGHT   GOOD
22    4765632     -1  !CAL VALIDATION HV5 R RIGHT FAIR ERROR 0.89 av...
23    4765632     -1  VALIDATE R 4POINT 0 RIGHT  at 400,300  OFFSET ...
24    4765632     -1  VALIDATE R 4POINT 1 RIGHT  at 400,51  OFFSET 0...
25    4765632     -1  VALIDATE R 4POINT 2 RIGHT  at 400,549  OFFSET ...
26    4765632     -1  VALIDATE R 4POINT 3 RIGHT  at 48,300  OFFSET 1...
27    4765633     -1  VALIDATE R 4POINT 4 RIGHT  at 752,300  OFFSET ...
28    4775931     -1  !CAL VALIDATION HV5 R RIGHT GOOD ERROR 0.45 av...
29    4775931     -1  VALIDATE R 4POINT 0 RIGHT  at 400,300  OFFSET ...
30    4775931     -1  VALIDATE R 4POINT 1 RIGHT  at 400,51  OFFSET 0...
31    4775931     -1  VALIDATE R 4POINT 2 RIGHT  at 400,549  OFFSET ...
32    4775931     -1  VALIDATE R 4POINT 3 RIGHT  at 48,300  OFFSET 0...
33    4775931     -1  VALIDATE R 4POINT 4 RIGHT  at 752,300  OFFSET ...
34    4886972     -1  NO Reply is disabled for function eyelink_cal_...
35    5315561     -1                                ET: start recording
36    5315567     -1                               RECCFG CR 1000 2 0 R
37    5315567     -1                                      ELCLCFG TOWER
38    5315567     -1                GAZE_COORDS 0.00 0.00 800.00 600.00
39    5315567     -1                                THRESHOLDS R 77 213
40    5315567     -1                             ELCL_PROC ELLIPSE  (5)
41    5315567     -1  ELCL_EFIT_PARAMS 1.01 4.00  0.15 0.05  0.65 0....
42    5315568     -1                         !MODE RECORD CR 1000 2 0 R
43    5316064     -1                                 ET: stop recording
44    5316065     -1                            ET: Start routine 'dot'
45    5316066     -1                            ET: Start routine 'dot'
46    5316066     -1                            ET: Start routine 'dot'
47    5316066     -1                            ET: Start routine 'dot'
48    5321057     -1                            ET: Start routine 'dot'
49    5321057     -1                            ET: Start routine 'dot'
50    5321058     -1                            ET: Start routine 'dot'
51    5321059     -1                            ET: Start routine 'dot'
52    5326057     -1                            ET: Start routine 'dot'
53    5326057     -1                            ET: Start routine 'dot'
54    5326057     -1                            ET: Start routine 'dot'
55    5326057     -1                            ET: Start routine 'dot'
56    5331057     -1                            ET: Start routine 'dot'
57    5331058     -1                            ET: Start routine 'dot'
58    5331059     -1                            ET: Start routine 'dot'
59    5331059     -1                            ET: Start routine 'dot'
60    5336057     -1                            ET: Start routine 'dot'
61    5336057     -1                            ET: Start routine 'dot'
62    5336057     -1                            ET: Start routine 'dot'
63    5336057     -1                            ET: Start routine 'dot'
64    5341057     -1                            ET: Start routine 'dot'
65    5341058     -1                            ET: Start routine 'dot'
66    5341058     -1                            ET: Start routine 'dot'
67    5341059     -1                            ET: Start routine 'dot'
68    5346058     -1                           ET: Start routine 'dots'
69    5346058     -1                                ET: dot moved down!
70    5351073     -1                               ET: dot moved right!
71    5356091     -1                                  ET: dot moved up!
72    5361107     -1                                ET: dot moved left!
73    5366124     -1                           ET: Start routine 'dots'
74    5366125     -1                                ET: dot moved down!
75    5371141     -1                               ET: dot moved right!
76    5376141     -1                                  ET: dot moved up!
77    5381141     -1                                ET: dot moved left!
78    5386158     -1                           ET: Start routine 'dots'
79    5386158     -1                                ET: dot moved down!

Index(['time', 'px_left', 'px_right', 'py_left', 'py_right', 'hx_left',
       'hx_right', 'hy_left', 'hy_right', 'pa_left', 'pa_right', 'gx_left',
       'gx_right', 'gy_left', 'gy_right', 'rx', 'ry', 'gxvel_left',
       'gxvel_right', 'gyvel_left', 'gyvel_right', 'hxvel_left', 'hxvel_right',
       'hyvel_left', 'hyvel_right', 'rxvel_left', 'rxvel_right', 'ryvel_left',
       'ryvel_right', 'fgxvel', 'fgyvel', 'fhxvel', 'fhyvel', 'frxvel',
       'fryvel', 'flags', 'input', 'buttons', 'htype', 'errors'],
      dtype='object')

# 1 Parsing the messages

In [7]:
messages = messages.rename(
    columns={c: c.strip() for c in messages.columns.values}
).drop_duplicates()

In [8]:
# Extract calibration headers
_cal_hdr = ori_messages.trialid.str.startswith("!CAL")
calibration = ori_messages[_cal_hdr]
# messages = messages.drop(messages.index[_cal_hdr])
print(calibration)

    timestamp  trial                                            trialid
1     4752963     -1  !CAL \n>>>>>>> CALIBRATION (HV5,P-CR) FOR RIGH...
2     4752963     -1                           !CAL Calibration points:
3     4752963     -1                 !CAL -8.1, -40.9         0,      0
4     4752963     -1                 !CAL -6.9, -55.7         0,  -1726
5     4752963     -1                 !CAL -8.5, -24.7         0,   1726
6     4752963     -1                !CAL -32.0, -37.7     -2439,      0
7     4752963     -1                !CAL  17.0, -39.1      2439,      0
8     4752963     -1  !CAL eye check box: (L,R,T,B)\n\t  -37    22  ...
9     4752963     -1  !CAL href cal range: (L,R,T,B)\n\t-3659  3659 ...
10    4752963     -1  !CAL Cal coeff:(X=a+bx+cy+dxx+eyy,Y=f+gx+goaly...
11    4752963     -1    !CAL Prenormalize: offx, offy = -8.0857 -40.878
12    4752963     -1         !CAL Gains: cx:97.645 lx:106.941 rx:96.066
13    4752963     -1         !CAL Gains: cy:84.279 ty:118.628 by:93.427
14    4752963     -1  !CAL Resolution (upd) at screen center: X=2.7,...
15    4752964     -1     !CAL Gain Change Proportion: X: 0.113 Y: 0.270
16    4752964     -1                    !CAL Gain Ratio (Gy/Gx) = 0.863
17    4752964     -1                     !CAL Bad Y/X gain ratio: 0.863
18    4752964     -1            !CAL PCR gain ratio(x,y) = 2.334, 2.075
19    4752964     -1             !CAL CR gain match(x,y) = 1.020, 1.020
20    4752964     -1                  !CAL Slip rotation correction OFF
21    4752965     -1                !CAL CALIBRATION HV5 R RIGHT   GOOD
22    4765632     -1  !CAL VALIDATION HV5 R RIGHT FAIR ERROR 0.89 av...
28    4775931     -1  !CAL VALIDATION HV5 R RIGHT GOOD ERROR 0.45 av...

In [9]:
# Extracting the StartTime and StopTime metadata.
message_first_trigger = '!MODE RECORD CR 1000 2 0 R'
message_last_trigger = 'ET: eye-tracker stopped'
metadata = {
    'StopTime': None,
    'StartTime': None
}

# Find Start time
start_rows = messages.trialid.str.contains(
    message_first_trigger, case=False, regex=True
)
stop_rows = messages.trialid.str.contains(
    message_last_trigger, case=False, regex=True
)


# Extract calibration headers
_cal_hdr = messages.trialid.str.startswith("!CAL")
calibration = messages[_cal_hdr]
messages = messages.drop(messages.index[_cal_hdr])

# Pick the LAST of the start messages
metadata["StartTime"] = (
    int(messages[start_rows].timestamp.values[-1])
    if start_rows.any()
    else None
)

# Pick the FIRST of the stop messages
metadata["StopTime"] = (
    int(messages[stop_rows].timestamp.values[0])
    if stop_rows.any()
    else None
)

# Drop start and stop messages from messages dataframe
messages = messages.loc[~start_rows & ~stop_rows, :]

metadata

/tmp/ipykernel_4104226/906092332.py:25: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  int(messages[start_rows].timestamp.values[-1])

{'StopTime': None, 'StartTime': 5315568}

In [10]:
# Extracting basic metadata.
# !MODE RECORD CR 1000 2 0 R

mode_record = messages.trialid.str.startswith("!MODE RECORD")

meta_record = {
    "freq": DEFAULT_FREQUENCY,
    "mode": DEFAULT_MODE,
    "eye": DEFAULT_EYE,
}

if mode_record.any():
    try:
        meta_record = re.match(
            r"\!MODE RECORD (?P<mode>\w+) (?P<freq>\d+) \d \d (?P<eye>[RL]+)",
            messages[mode_record].trialid.iloc[-1].strip(),
        ).groupdict()

        meta_record["eye"] = EYE_CODE_MAP[meta_record["eye"]]
        meta_record["mode"] = (
            "P-CR" if meta_record["mode"] == "CR" else meta_record["mode"]
        )
    except AttributeError:
        warn(
            "Error extracting !MODE RECORD message, "
            "using default frequency, mode, and eye"
        )
    finally:
        messages = messages.loc[~mode_record]

eye = (
    ("right", "left") if meta_record["eye"] == "both" else (meta_record["eye"],)
)

metadata["SamplingFrequency"] = int(meta_record["freq"])
metadata["EyeTrackingMethod"] = meta_record["mode"]
metadata["RecordedEye"] = meta_record["eye"]

In [11]:
# Extracting screen parameters.
# GAZE_COORDS 0.00 0.00 800.00 600.00

# Extract GAZE_COORDS message signaling start of recording
gaze_msg = messages.trialid.str.startswith("GAZE_COORDS")

metadata["ScreenAOIDefinition"] = [
    "square",
    DEFAULT_SCREEN,
]
if gaze_msg.any():
    try:
        gaze_record = re.match(
            r"GAZE_COORDS (\d+\.\d+) (\d+\.\d+) (\d+\.\d+) (\d+\.\d+)",
            messages[gaze_msg].trialid.iloc[-1].strip(),
        ).groups()
        metadata["ScreenAOIDefinition"][1] = [
            int(round(float(gaze_record[0]))),
            int(round(float(gaze_record[2]))),
            int(round(float(gaze_record[1]))),
            int(round(float(gaze_record[3]))),
        ]
    except AttributeError:
        warn("Error extracting GAZE_COORDS")
    finally:
        messages = messages.loc[~gaze_msg]
        
print(metadata)

{'StopTime': None, 'StartTime': 5315568, 'SamplingFrequency': 1000, 'EyeTrackingMethod': 'P-CR', 'RecordedEye': 'right', 'ScreenAOIDefinition': ['square', [0, 800, 0, 600]]}

In [12]:
# Extracting parameters of the pupil fit model.
# ELCL_PROC ELLIPSE (5)
# ELCL_EFIT_PARAMS 1.01 4.00  0.15 0.05  0.65 0.65  0.00 0.00 0.30
# Extract ELCL_PROC AND ELCL_EFIT_PARAMS to extract pupil fit method
pupilfit_msg = messages.trialid.str.startswith("ELCL_PROC")

if pupilfit_msg.any():
    try:
        pupilfit_method = [
            val
            for val in messages[pupilfit_msg]
            .trialid.iloc[-1]
            .strip()
            .split(" ")[1:]
            if val
        ]
        metadata["PupilFitMethod"] = pupilfit_method[0].lower()
        metadata["PupilFitMethodNumberOfParameters"] = int(
            pupilfit_method[1].strip("(").strip(")")
        )
    except AttributeError:
        warn("Error extracting ELCL_PROC (pupil fitting method)")
    finally:
        messages = messages.loc[~pupilfit_msg]

pupilfit_msg_params = messages.trialid.str.startswith("ELCL_EFIT_PARAMS")
if pupilfit_msg_params.any():
    rows = messages[pupilfit_msg_params]
    row = rows.trialid.values[-1].strip().split(" ")[1:]
    try:
        metadata["PupilFitParameters"] = [
            tuple(float(val) for val in vals)
            for k, vals in groupby(row, key=bool)
            if k
        ]
    except AttributeError:
        warn("Error extracting ELCL_EFIT_PARAMS (pupil fitting parameters)")
    finally:
        messages = messages.loc[~pupilfit_msg_params]
        
metadata

{'StopTime': None,
 'StartTime': 5315568,
 'SamplingFrequency': 1000,
 'EyeTrackingMethod': 'P-CR',
 'RecordedEye': 'right',
 'ScreenAOIDefinition': ['square', [0, 800, 0, 600]],
 'PupilFitMethod': 'ellipse',
 'PupilFitMethodNumberOfParameters': 5,
 'PupilFitParameters': [(1.01, 4.0),
  (0.15, 0.05),
  (0.65, 0.65),
  (0.0, 0.0, 0.3)]}

In [13]:
# Calibration validation.
# VALIDATE R 4POINT 4 RIGHT at 752,300 OFFSET 0.35 deg. -8.7,-3.8 pix.
# Extract VALIDATE messages for a calibration validation
validation_msg = messages.trialid.str.startswith("VALIDATE")

if validation_msg.any():
    metadata["ValidationPosition"] = []
    metadata["ValidationErrors"] = []

for i_row, validate_row in enumerate(messages[validation_msg].trialid.values):
    prefix, suffix = validate_row.split("OFFSET")
    validation_eye = (
        f"eye{eye.index('right') + 1}"
        if "RIGHT" in prefix
        else f"eye{eye.index('left') + 1}"
    )
    validation_coords = [
        int(val.strip())
        for val in prefix.rsplit("at", 1)[-1].split(",")
        if val.strip()
    ]
    metadata["ValidationPosition"].append(
        [validation_eye, validation_coords]
    )

    validate_values = [
        float(val)
        for val in re.match(
            r"(-?\d+\.\d+) deg\.\s+(-?\d+\.\d+),(-?\d+\.\d+) pix\.",
            suffix.strip(),
        ).groups()
    ]

    metadata["ValidationErrors"].append(
        (validation_eye, validate_values[0], tuple(validate_values[1:]))
    )
messages = messages.loc[~validation_msg]

print(messages)
print(metadata)

     timestamp  trial                                            trialid
0      4702585     -1                        ET: Start experiment 'dots'
34     4886972     -1  NO Reply is disabled for function eyelink_cal_...
35     5315561     -1                                ET: start recording
36     5315567     -1                               RECCFG CR 1000 2 0 R
37     5315567     -1                                      ELCLCFG TOWER
..         ...    ...                                                ...
237    5967472     -1                            ET: Start routine 'dot'
238    5972470     -1                            ET: Start routine 'dot'
240    5972471     -1                            ET: Start routine 'dot'
242    5977468     -1                 ET: Prepare to start routine 'end'
243    5989502     -1                            ET: eye tracker stopped

[185 rows x 3 columns]
{'StopTime': None, 'StartTime': 5315568, 'SamplingFrequency': 1000, 'EyeTrackingMethod': 'P-CR', 'RecordedEye': 'right', 'ScreenAOIDefinition': ['square', [0, 800, 0, 600]], 'PupilFitMethod': 'ellipse', 'PupilFitMethodNumberOfParameters': 5, 'PupilFitParameters': [(1.01, 4.0), (0.15, 0.05), (0.65, 0.65), (0.0, 0.0, 0.3)], 'ValidationPosition': [['eye1', [400, 300]], ['eye1', [400, 51]], ['eye1', [400, 549]], ['eye1', [48, 300]], ['eye1', [752, 300]], ['eye1', [400, 300]], ['eye1', [400, 51]], ['eye1', [400, 549]], ['eye1', [48, 300]], ['eye1', [752, 300]]], 'ValidationErrors': [('eye1', 0.44, (9.8, -13.5)), ('eye1', 0.6, (-2.4, 22.6)), ('eye1', 1.28, (19.1, -44.7)), ('eye1', 1.93, (70.1, -21.5)), ('eye1', 0.16, (3.8, -4.9)), ('eye1', 0.37, (-8.2, -11.5)), ('eye1', 0.52, (-4.1, 19.2)), ('eye1', 0.31, (10.8, -5.2)), ('eye1', 0.95, (-3.5, -36.1)), ('eye1', 0.36, (8.4, -11.0))]}

In [14]:
# Extracting final bits of metadata.
# Extract THRESHOLDS messages prior recording and process last
thresholds_msg = messages.trialid.str.startswith("THRESHOLDS")
if thresholds_msg.any():
    metadata["PupilThreshold"] = [None] * len(eye)
    metadata["CornealReflectionThreshold"] = [None] * len(eye)
    thresholds_chunks = (
        messages[thresholds_msg].trialid.iloc[-1].strip().split(" ")[1:]
    )
    eye_index = eye.index(EYE_CODE_MAP[thresholds_chunks[0]])
    metadata["PupilThreshold"][eye_index] = int(thresholds_chunks[-2])
    metadata["CornealReflectionThreshold"][eye_index] = int(
        thresholds_chunks[-1]
    )
messages = messages.loc[~thresholds_msg]
print(messages)
print(metadata)

     timestamp  trial                                            trialid
0      4702585     -1                        ET: Start experiment 'dots'
34     4886972     -1  NO Reply is disabled for function eyelink_cal_...
35     5315561     -1                                ET: start recording
36     5315567     -1                               RECCFG CR 1000 2 0 R
37     5315567     -1                                      ELCLCFG TOWER
..         ...    ...                                                ...
237    5967472     -1                            ET: Start routine 'dot'
238    5972470     -1                            ET: Start routine 'dot'
240    5972471     -1                            ET: Start routine 'dot'
242    5977468     -1                 ET: Prepare to start routine 'end'
243    5989502     -1                            ET: eye tracker stopped

[184 rows x 3 columns]
{'StopTime': None, 'StartTime': 5315568, 'SamplingFrequency': 1000, 'EyeTrackingMethod': 'P-CR', 'RecordedEye': 'right', 'ScreenAOIDefinition': ['square', [0, 800, 0, 600]], 'PupilFitMethod': 'ellipse', 'PupilFitMethodNumberOfParameters': 5, 'PupilFitParameters': [(1.01, 4.0), (0.15, 0.05), (0.65, 0.65), (0.0, 0.0, 0.3)], 'ValidationPosition': [['eye1', [400, 300]], ['eye1', [400, 51]], ['eye1', [400, 549]], ['eye1', [48, 300]], ['eye1', [752, 300]], ['eye1', [400, 300]], ['eye1', [400, 51]], ['eye1', [400, 549]], ['eye1', [48, 300]], ['eye1', [752, 300]]], 'ValidationErrors': [('eye1', 0.44, (9.8, -13.5)), ('eye1', 0.6, (-2.4, 22.6)), ('eye1', 1.28, (19.1, -44.7)), ('eye1', 1.93, (70.1, -21.5)), ('eye1', 0.16, (3.8, -4.9)), ('eye1', 0.37, (-8.2, -11.5)), ('eye1', 0.52, (-4.1, 19.2)), ('eye1', 0.31, (10.8, -5.2)), ('eye1', 0.95, (-3.5, -36.1)), ('eye1', 0.36, (8.4, -11.0))], 'PupilThreshold': [77], 'CornealReflectionThreshold': [213]}

In [15]:
# Flush the remaining messages as a metadata entry.
# Consume the remainder of messages

if not messages.empty:
    metadata["LoggedMessages"] = [
        (int(msg_timestamp), msg.strip())
        for msg_timestamp, msg in messages[["timestamp", "trialid"]].values
    ]
    
print(messages)
print(metadata)

     timestamp  trial                                            trialid
0      4702585     -1                        ET: Start experiment 'dots'
34     4886972     -1  NO Reply is disabled for function eyelink_cal_...
35     5315561     -1                                ET: start recording
36     5315567     -1                               RECCFG CR 1000 2 0 R
37     5315567     -1                                      ELCLCFG TOWER
..         ...    ...                                                ...
237    5967472     -1                            ET: Start routine 'dot'
238    5972470     -1                            ET: Start routine 'dot'
240    5972471     -1                            ET: Start routine 'dot'
242    5977468     -1                 ET: Prepare to start routine 'end'
243    5989502     -1                            ET: eye tracker stopped

[184 rows x 3 columns]
{'StopTime': None, 'StartTime': 5315568, 'SamplingFrequency': 1000, 'EyeTrackingMethod': 'P-CR', 'RecordedEye': 'right', 'ScreenAOIDefinition': ['square', [0, 800, 0, 600]], 'PupilFitMethod': 'ellipse', 'PupilFitMethodNumberOfParameters': 5, 'PupilFitParameters': [(1.01, 4.0), (0.15, 0.05), (0.65, 0.65), (0.0, 0.0, 0.3)], 'ValidationPosition': [['eye1', [400, 300]], ['eye1', [400, 51]], ['eye1', [400, 549]], ['eye1', [48, 300]], ['eye1', [752, 300]], ['eye1', [400, 300]], ['eye1', [400, 51]], ['eye1', [400, 549]], ['eye1', [48, 300]], ['eye1', [752, 300]]], 'ValidationErrors': [('eye1', 0.44, (9.8, -13.5)), ('eye1', 0.6, (-2.4, 22.6)), ('eye1', 1.28, (19.1, -44.7)), ('eye1', 1.93, (70.1, -21.5)), ('eye1', 0.16, (3.8, -4.9)), ('eye1', 0.37, (-8.2, -11.5)), ('eye1', 0.52, (-4.1, 19.2)), ('eye1', 0.31, (10.8, -5.2)), ('eye1', 0.95, (-3.5, -36.1)), ('eye1', 0.36, (8.4, -11.0))], 'PupilThreshold': [77], 'CornealReflectionThreshold': [213], 'LoggedMessages': [(4702585, "ET: Start experiment 'dots'"), (4886972, 'NO Reply is disabled for function eyelink_cal_result'), (5315561, 'ET: start recording'), (5315567, 'RECCFG CR 1000 2 0 R'), (5315567, 'ELCLCFG TOWER'), (5316064, 'ET: stop recording'), (5316065, "ET: Start routine 'dot'"), (5316066, "ET: Start routine 'dot'"), (5321057, "ET: Start routine 'dot'"), (5321058, "ET: Start routine 'dot'"), (5321059, "ET: Start routine 'dot'"), (5326057, "ET: Start routine 'dot'"), (5331057, "ET: Start routine 'dot'"), (5331058, "ET: Start routine 'dot'"), (5331059, "ET: Start routine 'dot'"), (5336057, "ET: Start routine 'dot'"), (5341057, "ET: Start routine 'dot'"), (5341058, "ET: Start routine 'dot'"), (5341059, "ET: Start routine 'dot'"), (5346058, "ET: Start routine 'dots'"), (5346058, 'ET: dot moved down!'), (5351073, 'ET: dot moved right!'), (5356091, 'ET: dot moved up!'), (5361107, 'ET: dot moved left!'), (5366124, "ET: Start routine 'dots'"), (5366125, 'ET: dot moved down!'), (5371141, 'ET: dot moved right!'), (5376141, 'ET: dot moved up!'), (5381141, 'ET: dot moved left!'), (5386158, "ET: Start routine 'dots'"), (5386158, 'ET: dot moved down!'), (5391175, 'ET: dot moved up!'), (5396192, 'ET: dot moved left!'), (5401209, 'ET: dot moved right!'), (5406211, "ET: Start routine 'dots'"), (5406212, 'ET: dot moved left!'), (5411225, 'ET: dot moved up!'), (5416242, 'ET: dot moved right!'), (5421242, 'ET: dot moved down!'), (5426259, "ET: Start routine 'dots'"), (5426260, 'ET: dot moved down!'), (5431276, 'ET: dot moved up!'), (5436275, 'ET: dot moved right!'), (5441292, 'ET: dot moved left!'), (5446310, "ET: Start routine 'dots'"), (5446310, 'ET: dot moved right!'), (5451325, 'ET: dot moved down!'), (5456327, 'ET: dot moved left!'), (5461343, 'ET: dot moved up!'), (5466344, "ET: Start routine 'dots'"), (5466344, 'ET: dot moved up!'), (5471360, 'ET: dot moved left!'), (5476360, 'ET: dot moved down!'), (5481376, 'ET: dot moved right!'), (5486377, "ET: Start routine 'dots'"), (5486378, 'ET: dot moved right!'), (5491393, 'ET: dot moved left!'), (5496410, 'ET: dot moved down!'), (5501427, 'ET: dot moved up!'), (5506428, "ET: Start routine 'dots'"), (5506429, 'ET: dot moved right!'), (5511445, 'ET: dot moved up!'), (5516461, 'ET: dot moved left!'), (5521477, 'ET: dot moved down!'), (5526479, "ET: Start routine 'dots'"), (5526480, 'ET: dot moved right!'), (5531494, 'ET: dot moved down!'), (5536511, 'ET: dot moved left!'), (5541527, 'ET: dot moved up!'), (5546546, "ET: Start routine 'dots'"), (5546546, 'ET: dot moved right!'), (5551561, 'ET: dot moved up!'), (5556578, 'ET: dot moved down!'), (5561595, 'ET: dot moved left!'), (5566612, "ET: Start routine 'dots'"), (5566612, 'ET: dot moved right!'), (5571628, 'ET: dot moved up!'), (5576628, 'ET: dot moved down!'), (5581644, 'ET: dot moved left!'), (5586645, "ET: Start routine 'dots'"), (5586646, 'ET: dot moved up!'), (5591662, 'ET: dot moved down!'), (5596678, 'ET: dot moved right!'), (5601678, 'ET: dot moved left!'), (5606696, "ET: Start routine 'dots'"), (5606696, 'ET: dot moved up!'), (5611696, 'ET: dot moved down!'), (5616712, 'ET: dot moved left!'), (5621728, 'ET: dot moved right!'), (5626731, "ET: Start routine 'dots'"), (5626731, 'ET: dot moved up!'), (5631746, 'ET: dot moved right!'), (5636746, 'ET: dot moved left!'), (5641763, 'ET: dot moved down!'), (5646764, "ET: Start routine 'dots'"), (5646764, 'ET: dot moved left!'), (5651780, 'ET: dot moved up!'), (5656780, 'ET: dot moved down!'), (5661797, 'ET: dot moved right!'), (5666814, "ET: Start routine 'dots'"), (5666815, 'ET: dot moved right!'), (5671830, 'ET: dot moved left!'), (5676831, 'ET: dot moved up!'), (5681847, 'ET: dot moved down!'), (5686847, "ET: Start routine 'dots'"), (5686847, 'ET: dot moved right!'), (5691863, 'ET: dot moved up!'), (5696864, 'ET: dot moved left!'), (5701864, 'ET: dot moved down!'), (5706883, "ET: Start routine 'dots'"), (5706884, 'ET: dot moved up!'), (5711898, 'ET: dot moved right!'), (5716914, 'ET: dot moved left!'), (5721931, 'ET: dot moved down!'), (5726932, "ET: Start routine 'dots'"), (5726933, 'ET: dot moved down!'), (5731948, 'ET: dot moved left!'), (5736965, 'ET: dot moved up!'), (5741981, 'ET: dot moved right!'), (5746982, "ET: Start routine 'dots'"), (5746983, 'ET: dot moved up!'), (5751998, 'ET: dot moved right!'), (5757014, 'ET: dot moved down!'), (5762031, 'ET: dot moved left!'), (5767049, "ET: Start routine 'dots'"), (5767049, 'ET: dot moved right!'), (5772066, 'ET: dot moved down!'), (5777081, 'ET: dot moved left!'), (5782098, 'ET: dot moved up!'), (5787115, "ET: Start routine 'dots'"), (5787115, 'ET: dot moved left!'), (5792135, 'ET: dot moved down!'), (5797149, 'ET: dot moved right!'), (5802165, 'ET: dot moved up!'), (5807167, "ET: Start routine 'dots'"), (5807167, 'ET: dot moved down!'), (5812182, 'ET: dot moved up!'), (5817200, 'ET: dot moved right!'), (5822215, 'ET: dot moved left!'), (5827217, "ET: Start routine 'dots'"), (5827217, 'ET: dot moved right!'), (5832233, 'ET: dot moved left!'), (5837249, 'ET: dot moved up!'), (5842250, 'ET: dot moved down!'), (5847268, "ET: Start routine 'dots'"), (5847268, 'ET: dot moved right!'), (5852283, 'ET: dot moved up!'), (5857299, 'ET: dot moved left!'), (5862300, 'ET: dot moved down!'), (5867302, "ET: Start routine 'dots'"), (5867302, 'ET: dot moved right!'), (5872316, 'ET: dot moved down!'), (5877333, 'ET: dot moved left!'), (5882334, 'ET: dot moved up!'), (5887351, "ET: Start routine 'dots'"), (5887352, 'ET: dot moved left!'), (5892367, 'ET: dot moved up!'), (5897383, 'ET: dot moved down!'), (5902384, 'ET: dot moved right!'), (5907385, "ET: Start routine 'dots'"), (5907385, 'ET: dot moved down!'), (5912401, 'ET: dot moved up!'), (5917418, 'ET: dot moved left!'), (5922419, 'ET: dot moved right!'), (5927436, "ET: Start routine 'dots'"), (5927436, 'ET: dot moved right!'), (5932451, 'ET: dot moved down!'), (5937451, 'ET: dot moved left!'), (5942468, 'ET: dot moved up!'), (5947469, "ET: Start routine 'dot'"), (5947470, "ET: Start routine 'dot'"), (5952470, "ET: Start routine 'dot'"), (5952471, "ET: Start routine 'dot'"), (5957469, "ET: Start routine 'dot'"), (5957470, "ET: Start routine 'dot'"), (5962470, "ET: Start routine 'dot'"), (5962471, "ET: Start routine 'dot'"), (5967470, "ET: Start routine 'dot'"), (5967471, "ET: Start routine 'dot'"), (5967472, "ET: Start routine 'dot'"), (5972470, "ET: Start routine 'dot'"), (5972471, "ET: Start routine 'dot'"), (5977468, "ET: Prepare to start routine 'end'"), (5989502, 'ET: eye tracker stopped')]}

# 2 Parsing the recording dataframe

In [16]:
recording = ori_recording
ori_recording

,time,px_left,px_right,py_left,py_right,hx_left,hx_right,hy_left,hy_right,pa_left,...,fgyvel,fhxvel,fhyvel,frxvel,fryvel,flags,input,buttons,htype,errors
0,5315568.0,-32768.0,362.0,-32768.0,-3864.0,-32768.0,1115.0,-32768.0,1068.0,-32768.0,...,0.0,4.162697e-41,0.0,4.591354e-41,4.162697e-41,32641.0,32768.0,0.0,-32768.0,0.0
1,5315569.0,-32768.0,359.0,-32768.0,-3864.0,-32768.0,1113.0,-32768.0,1068.0,-32768.0,...,0.0,4.162697e-41,0.0,4.591354e-41,4.162697e-41,24449.0,32768.0,0.0,-32768.0,0.0
2,5315570.0,-32768.0,355.0,-32768.0,-3869.0,-32768.0,1109.0,-32768.0,1064.0,-32768.0,...,0.0,4.162697e-41,0.0,4.591354e-41,4.162697e-41,24449.0,32768.0,0.0,-32768.0,0.0
3,5315571.0,-32768.0,351.0,-32768.0,-3875.0,-32768.0,1107.0,-32768.0,1060.0,-32768.0,...,0.0,4.162697e-41,0.0,4.591354e-41,4.162697e-41,24449.0,32768.0,0.0,-32768.0,0.0
4,5315572.0,-32768.0,349.0,-32768.0,-3880.0,-32768.0,1105.0,-32768.0,1055.0,-32768.0,...,0.0,4.162697e-41,0.0,4.591354e-41,4.162697e-41,24449.0,32768.0,0.0,-32768.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662897,5978465.0,-32768.0,-32768.0,-32768.0,-32768.0,-32768.0,-7936.0,-32768.0,-7936.0,-32768.0,...,NaN,0.000000e+00,0.0,4.591354e-41,4.162697e-41,24449.0,32768.0,0.0,-32768.0,0.0
662898,5978466.0,-32768.0,-32768.0,-32768.0,-32768.0,-32768.0,-7936.0,-32768.0,-7936.0,-32768.0,...,NaN,0.000000e+00,0.0,4.591354e-41,4.162697e-41,24449.0,32768.0,0.0,-32768.0,0.0
662899,5978467.0,-32768.0,-32768.0,-32768.0,-32768.0,-32768.0,-7936.0,-32768.0,-7936.0,-32768.0,...,NaN,0.000000e+00,0.0,4.591354e-41,4.162697e-41,24449.0,32768.0,0.0,-32768.0,0.0
662900,5978468.0,-32768.0,-32768.0,-32768.0,-32768.0,-32768.0,-7936.0,-32768.0,-7936.0,-32768.0,...,NaN,0.000000e+00,0.0,4.591354e-41,4.162697e-41,32641.0,32768.0,0.0,-32768.0,0.0
662901,5978469.0,-32768.0,-32768.0,-32768.0,-32768.0,-32768.0,-7936.0,-32768.0,-7936.0,-32768.0,...,NaN,0.000000e+00,0.0,4.591354e-41,4.162697e-41,24449.0,32768.0,0.0,-32768.0,0.0

In [17]:
# Curation of the input dataframe
# Normalize timestamps (should be int and strictly positive)
recording = recording.astype({"time": int})
recording = recording[recording["time"] > 0]
raw_recording_len = len(recording)
print(f'raw_recording length: {raw_recording_len}')

recording = recording.rename(
    columns={
#         # Fix buggy header names generated by pyedfread
#         "fhxyvel": "fhxvel",
#         "frxyvel": "frxvel",
        # Normalize weird header names generated by pyedfread
        "rx": "screen_ppdeg_x_coordinate",
        "ry": "screen_ppdeg_y_coordinate",
        # Convert some BIDS columns
        "time": "timestamp",
    }
)

# Split extra columns from the dataframe
extra = recording[["flags", "input", "htype"]]
recording = recording.drop(columns=["flags", "input", "htype"])
print(len(recording))

# Remove columns that are always very close to zero
recording = recording.loc[:, (recording.abs() > 1e-8).any(axis=0)]
# Remove columns that are always 1e8 or more
recording = recording.loc[:, (recording.abs() < 1e8).any(axis=0)]
# Replace unreasonably high values with NaNs
recording = recording.replace({1e8: np.nan})

assert len(recording) == raw_recording_len

raw_recording length: 662902
662902

In [18]:
# Remove columns that do not apply (e.g., only one eye recorded).
# Drop one eye's columns if not interested in "both"
print(f'The eye we take care of {eye}')
remove_eye = set(("left", "right")) - set(eye)
if remove_eye:
    remove_eye = remove_eye.pop()  # Drop set decoration
    recording = recording.reindex(
        columns=[c for c in recording.columns if remove_eye not in c]
    )
    
columns = recording.columns
print("Columns:")
print(columns)
recording

The eye we take care of ('right',)
Columns:
Index(['timestamp', 'px_right', 'py_right', 'hx_right', 'hy_right', 'pa_right',
       'gx_right', 'gy_right', 'screen_ppdeg_x_coordinate',
       'screen_ppdeg_y_coordinate', 'gxvel_right', 'gyvel_right',
       'hxvel_right', 'hyvel_right', 'rxvel_right', 'ryvel_right', 'fgxvel'],
      dtype='object')

,timestamp,px_right,py_right,hx_right,hy_right,pa_right,gx_right,gy_right,screen_ppdeg_x_coordinate,screen_ppdeg_y_coordinate,gxvel_right,gyvel_right,hxvel_right,hyvel_right,rxvel_right,ryvel_right,fgxvel
0,5315568,362.0,-3864.0,1115.0,1068.0,1342.0,560.900024,454.100006,38.000000,38.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.0
1,5315569,359.0,-3864.0,1113.0,1068.0,1341.0,560.599976,454.200012,38.000000,38.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,5315570,355.0,-3869.0,1109.0,1064.0,1340.0,560.099976,453.600006,38.000000,38.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.0
3,5315571,351.0,-3875.0,1107.0,1060.0,1336.0,559.700012,452.899994,38.000000,38.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.0
4,5315572,349.0,-3880.0,1105.0,1055.0,1332.0,559.500000,452.299988,38.000000,38.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
662897,5978465,-32768.0,-32768.0,-7936.0,-7936.0,0.0,NaN,NaN,38.200001,38.700001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
662898,5978466,-32768.0,-32768.0,-7936.0,-7936.0,0.0,NaN,NaN,38.200001,38.700001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
662899,5978467,-32768.0,-32768.0,-7936.0,-7936.0,0.0,NaN,NaN,38.200001,38.700001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
662900,5978468,-32768.0,-32768.0,-7936.0,-7936.0,0.0,NaN,NaN,38.200001,38.700001,NaN,NaN,NaN,NaN,NaN,NaN,NaN
662901,5978469,-32768.0,-32768.0,-7936.0,-7936.0,0.0,NaN,NaN,38.200001,38.700001,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# Clean-up pupil size and gaze position. 
# These are the parameters we most likely we care for, so special curation is applied:
screen_resolution = [800, 600]

for eyenum, eyename in enumerate(eye):
    # Clean-up implausible values for pupil area (pa)
    recording.loc[
        recording[f"pa_{eyename}"] < 1, f"pa_{eyename}"
    ] = np.nan
    recording = recording.rename(
        columns={f"pa_{eyename}": f"eye{eyenum + 1}_pupil_size"}
    )
    print(f"pa_{eyename} renamed as: eye{eyenum + 1}_pupil_size")
    # Clean-up implausible values for gaze x position
    recording.loc[
        (recording[f"gx_{eyename}"] < 0)
        | (recording[f"gx_{eyename}"] > screen_resolution[0]),
        f"gx_{eyename}",
    ] = np.nan
    # Clean-up implausible values for gaze y position
    recording.loc[
        (recording[f"gy_{eyename}"] <= 0)
        | (recording[f"gy_{eyename}"] > screen_resolution[1]),
        f"gy_{eyename}",
    ] = np.nan
    
print(recording)
assert len(recording) == raw_recording_len

pa_right renamed as: eye1_pupil_size
        timestamp  px_right  py_right  hx_right  hy_right  eye1_pupil_size  \
0         5315568     362.0   -3864.0    1115.0    1068.0           1342.0
1         5315569     359.0   -3864.0    1113.0    1068.0           1341.0
2         5315570     355.0   -3869.0    1109.0    1064.0           1340.0
3         5315571     351.0   -3875.0    1107.0    1060.0           1336.0
4         5315572     349.0   -3880.0    1105.0    1055.0           1332.0
...           ...       ...       ...       ...       ...              ...
662897    5978465  -32768.0  -32768.0   -7936.0   -7936.0              NaN
662898    5978466  -32768.0  -32768.0   -7936.0   -7936.0              NaN
662899    5978467  -32768.0  -32768.0   -7936.0   -7936.0              NaN
662900    5978468  -32768.0  -32768.0   -7936.0   -7936.0              NaN
662901    5978469  -32768.0  -32768.0   -7936.0   -7936.0              NaN

          gx_right    gy_right  screen_ppdeg_x_coordinate  \
0       560.900024  454.100006                  38.000000
1       560.599976  454.200012                  38.000000
2       560.099976  453.600006                  38.000000
3       559.700012  452.899994                  38.000000
4       559.500000  452.299988                  38.000000
...            ...         ...                        ...
662897         NaN         NaN                  38.200001
662898         NaN         NaN                  38.200001
662899         NaN         NaN                  38.200001
662900         NaN         NaN                  38.200001
662901         NaN         NaN                  38.200001

        screen_ppdeg_y_coordinate  gxvel_right  gyvel_right  hxvel_right  \
0                       38.000000          NaN          NaN          NaN
1                       38.000000          NaN          NaN          NaN
2                       38.000000          NaN          NaN          NaN
3                       38.000000          NaN          NaN          NaN
4                       38.000000          NaN          NaN          NaN
...                           ...          ...          ...          ...
662897                  38.700001          NaN          NaN          NaN
662898                  38.700001          NaN          NaN          NaN
662899                  38.700001          NaN          NaN          NaN
662900                  38.700001          NaN          NaN          NaN
662901                  38.700001          NaN          NaN          NaN

        hyvel_right  rxvel_right  ryvel_right  fgxvel
0               NaN          NaN          NaN     0.0
1               NaN          NaN          NaN     0.0
2               NaN          NaN          NaN     0.0
3               NaN          NaN          NaN     0.0
4               NaN          NaN          NaN     0.0
...             ...          ...          ...     ...
662897          NaN          NaN          NaN     NaN
662898          NaN          NaN          NaN     NaN
662899          NaN          NaN          NaN     NaN
662900          NaN          NaN          NaN     NaN
662901          NaN          NaN          NaN     NaN

[662902 rows x 17 columns]

In [20]:
# Munging columns to comply with BIDS. 
# At this point, the dataframe is almost ready for writing out as BIDS.
# Interpolate BIDS column names
columns = list(
    set(recording.columns)
    - set(
        (
            "timestamp",
            "screen_ppdeg_x_coordinate",
            "screen_ppdeg_y_coordinate",
            "eye1_pupil_size",#pa
            "eye2_pupil_size",#pa
        )
    )
)
bids_columns = []
for eyenum, eyename in enumerate(eye):
    for name in columns:
        colprefix = f"eye{eyenum + 1}" if name.endswith(f"_{eyename}") else ""
        _newname = name.split("_")[0]
        _newname = re.sub(r"([xy])$", r"_\1_coordinate", _newname)
        _newname = re.sub(r"([xy])vel$", r"_\1_velocity", _newname)
        _newname = _newname.split("_", 1)
        _newname[0] = EDF2BIDS_COLUMNS[_newname[0]]
        _newname.insert(0, colprefix)
        bids_columns.append("_".join((_n for _n in _newname if _n)))

# Rename columns to be BIDS-compliant
recording = recording.rename(columns=dict(zip(columns, bids_columns)))

# Reorder columns to render nicely (tracking first, pupil size after)
columns = sorted(
    set(recording.columns.values).intersection(BIDS_COLUMNS_ORDER),
    key=lambda entry: BIDS_COLUMNS_ORDER.index(entry),
)
columns += [c for c in recording.columns.values if c not in columns]
recording = recording.reindex(columns=columns)

print(recording)
assert len(recording) == raw_recording_len

        eye1_x_coordinate  eye1_y_coordinate  eye1_pupil_size  \
0              560.900024         454.100006           1342.0
1              560.599976         454.200012           1341.0
2              560.099976         453.600006           1340.0
3              559.700012         452.899994           1336.0
4              559.500000         452.299988           1332.0
...                   ...                ...              ...
662897                NaN                NaN              NaN
662898                NaN                NaN              NaN
662899                NaN                NaN              NaN
662900                NaN                NaN              NaN
662901                NaN                NaN              NaN

        eye1_pupil_x_coordinate  eye1_pupil_y_coordinate  \
0                         362.0                  -3864.0
1                         359.0                  -3864.0
2                         355.0                  -3869.0
3                         351.0                  -3875.0
4                         349.0                  -3880.0
...                         ...                      ...
662897                 -32768.0                 -32768.0
662898                 -32768.0                 -32768.0
662899                 -32768.0                 -32768.0
662900                 -32768.0                 -32768.0
662901                 -32768.0                 -32768.0

        eye1_href_x_coordinate  eye1_href_y_coordinate  eye1_x_velocity  \
0                       1115.0                  1068.0              NaN
1                       1113.0                  1068.0              NaN
2                       1109.0                  1064.0              NaN
3                       1107.0                  1060.0              NaN
4                       1105.0                  1055.0              NaN
...                        ...                     ...              ...
662897                 -7936.0                 -7936.0              NaN
662898                 -7936.0                 -7936.0              NaN
662899                 -7936.0                 -7936.0              NaN
662900                 -7936.0                 -7936.0              NaN
662901                 -7936.0                 -7936.0              NaN

        eye1_y_velocity  eye1_href_x_velocity  eye1_href_y_velocity  \
0                   NaN                   NaN                   NaN
1                   NaN                   NaN                   NaN
2                   NaN                   NaN                   NaN
3                   NaN                   NaN                   NaN
4                   NaN                   NaN                   NaN
...                 ...                   ...                   ...
662897              NaN                   NaN                   NaN
662898              NaN                   NaN                   NaN
662899              NaN                   NaN                   NaN
662900              NaN                   NaN                   NaN
662901              NaN                   NaN                   NaN

        eye1_raw_x_velocity  eye1_raw_y_velocity  fast_x_velocity  \
0                       NaN                  NaN              0.0
1                       NaN                  NaN              0.0
2                       NaN                  NaN              0.0
3                       NaN                  NaN              0.0
4                       NaN                  NaN              0.0
...                     ...                  ...              ...
662897                  NaN                  NaN              NaN
662898                  NaN                  NaN              NaN
662899                  NaN                  NaN              NaN
662900                  NaN                  NaN              NaN
662901                  NaN                  NaN              NaN

        screen_ppdeg_x_coordinate  screen_ppdeg_y_coordinate  timestamp
0                       38.000000                  38.000000    5315568
1                       38.000000                  38.000000    5315569
2                       38.000000                  38.000000    5315570
3                       38.000000                  38.000000    5315571
4                       38.000000                  38.000000    5315572
...                           ...                        ...        ...
662897                  38.200001                  38.700001    5978465
662898                  38.200001                  38.700001    5978466
662899                  38.200001                  38.700001    5978467
662900                  38.200001                  38.700001    5978468
662901                  38.200001                  38.700001    5978469

[662902 rows x 17 columns]

# 3 Parsing the calibration messages

In [21]:
print(calibration)

    timestamp  trial                                            trialid
1     4752963     -1  !CAL \n>>>>>>> CALIBRATION (HV5,P-CR) FOR RIGH...
2     4752963     -1                           !CAL Calibration points:
3     4752963     -1                 !CAL -8.1, -40.9         0,      0
4     4752963     -1                 !CAL -6.9, -55.7         0,  -1726
5     4752963     -1                 !CAL -8.5, -24.7         0,   1726
6     4752963     -1                !CAL -32.0, -37.7     -2439,      0
7     4752963     -1                !CAL  17.0, -39.1      2439,      0
8     4752963     -1  !CAL eye check box: (L,R,T,B)\n\t  -37    22  ...
9     4752963     -1  !CAL href cal range: (L,R,T,B)\n\t-3659  3659 ...
10    4752963     -1  !CAL Cal coeff:(X=a+bx+cy+dxx+eyy,Y=f+gx+goaly...
11    4752963     -1    !CAL Prenormalize: offx, offy = -8.0857 -40.878
12    4752963     -1         !CAL Gains: cx:97.645 lx:106.941 rx:96.066
13    4752963     -1         !CAL Gains: cy:84.279 ty:118.628 by:93.427
14    4752963     -1  !CAL Resolution (upd) at screen center: X=2.7,...
15    4752964     -1     !CAL Gain Change Proportion: X: 0.113 Y: 0.270
16    4752964     -1                    !CAL Gain Ratio (Gy/Gx) = 0.863
17    4752964     -1                     !CAL Bad Y/X gain ratio: 0.863
18    4752964     -1            !CAL PCR gain ratio(x,y) = 2.334, 2.075
19    4752964     -1             !CAL CR gain match(x,y) = 1.020, 1.020
20    4752964     -1                  !CAL Slip rotation correction OFF
21    4752965     -1                !CAL CALIBRATION HV5 R RIGHT   GOOD
22    4765632     -1  !CAL VALIDATION HV5 R RIGHT FAIR ERROR 0.89 av...
28    4775931     -1  !CAL VALIDATION HV5 R RIGHT GOOD ERROR 0.45 av...

In [22]:
# Parse calibration metadata
metadata["CalibrationCount"] = 0
if not calibration.empty:
    warn("Calibration of more than one eye is not implemented")
    calibration.trialid = calibration.trialid.str.replace("!CAL", "")
    calibration.trialid = calibration.trialid.str.strip()

    metadata["CalibrationLog"] = list(
        zip(
            calibration.timestamp.values.astype(int),
            calibration.trialid.values,
        )
    )

    calibrations_msg = calibration.trialid.str.startswith(
        "VALIDATION"
    ) & calibration.trialid.str.contains("ERROR")
    metadata["CalibrationCount"] = calibrations_msg.sum()

    calibration_last = calibration.index[calibrations_msg][-1]
    try:
        meta_calib = re.match(
            r"VALIDATION (?P<ctype>[\w\d]+) (?P<eyeid>[RL]+) (?P<eye>RIGHT|LEFT) "
            r"(?P<result>\w+) ERROR (?P<avg>-?\d+\.\d+) avg\. (?P<max>-?\d+\.\d+) max\s+"
            r"OFFSET (?P<offsetdeg>-?\d+\.\d+) deg\. "
            r"(?P<offsetxpix>-?\d+\.\d+),(?P<offsetypix>-?\d+\.\d+) pix\.",
            calibration.loc[calibration_last, "trialid"].strip(),
        ).groupdict()

        metadata["CalibrationType"] = meta_calib["ctype"]
        metadata["AverageCalibrationError"] = [float(meta_calib["avg"])]
        metadata["MaximalCalibrationError"] = [float(meta_calib["max"])]
        metadata["CalibrationResultQuality"] = [meta_calib["result"]]
        metadata["CalibrationResultOffset"] = [
            float(meta_calib["offsetdeg"]),
            (float(meta_calib["offsetxpix"]), float(meta_calib["offsetypix"])),
        ]
        metadata["CalibrationResultOffsetUnits"] = ["deg", "pixels"]
    except AttributeError:
        warn("Calibration data found but unsuccessfully parsed for results")
        
        
print(calibration)

    timestamp  trial                                            trialid
1     4752963     -1  >>>>>>> CALIBRATION (HV5,P-CR) FOR RIGHT: <<<<...
2     4752963     -1                                Calibration points:
3     4752963     -1                      -8.1, -40.9         0,      0
4     4752963     -1                      -6.9, -55.7         0,  -1726
5     4752963     -1                      -8.5, -24.7         0,   1726
6     4752963     -1                     -32.0, -37.7     -2439,      0
7     4752963     -1                      17.0, -39.1      2439,      0
8     4752963     -1  eye check box: (L,R,T,B)\n\t  -37    22   -59 ...
9     4752963     -1  href cal range: (L,R,T,B)\n\t-3659  3659 -2588...
10    4752963     -1  Cal coeff:(X=a+bx+cy+dxx+eyy,Y=f+gx+goaly+ixx+...
11    4752963     -1         Prenormalize: offx, offy = -8.0857 -40.878
12    4752963     -1              Gains: cx:97.645 lx:106.941 rx:96.066
13    4752963     -1              Gains: cy:84.279 ty:118.628 by:93.427
14    4752963     -1    Resolution (upd) at screen center: X=2.7, Y=3.1
15    4752964     -1          Gain Change Proportion: X: 0.113 Y: 0.270
16    4752964     -1                         Gain Ratio (Gy/Gx) = 0.863
17    4752964     -1                          Bad Y/X gain ratio: 0.863
18    4752964     -1                 PCR gain ratio(x,y) = 2.334, 2.075
19    4752964     -1                  CR gain match(x,y) = 1.020, 1.020
20    4752964     -1                       Slip rotation correction OFF
21    4752965     -1                     CALIBRATION HV5 R RIGHT   GOOD
22    4765632     -1  VALIDATION HV5 R RIGHT FAIR ERROR 0.89 avg. 1....
28    4775931     -1  VALIDATION HV5 R RIGHT GOOD ERROR 0.45 avg. 0....

/tmp/ipykernel_4104226/3407936680.py:4: UserWarning: Calibration of more than one eye is not implemented
  warn("Calibration of more than one eye is not implemented")

# 4 Parsing the events dataframe

In [23]:
# events[
#     events["type"] == "saccade"
# ]

In [24]:
# print(events)
print(recording)

# Process events: first generate empty columns
recording["eye1_fixation"] = 0
recording["eye1_saccade"] = 0
recording["eye1_blink"] = 0

# Add fixations
for _, fixation_event in events[
    events["type"] == "fixation"
].iterrows():
    recording.loc[
        (recording["timestamp"] >= fixation_event["start"])
        & (recording["timestamp"] <= fixation_event["end"]),
        "eye1_fixation",
    ] = 1

# Add saccades, and blinks, which are a sub-event of saccades
for _, saccade_event in events[
    events["type"] == "saccade"
].iterrows():
    recording.loc[
        (recording["timestamp"] >= saccade_event["start"])
        & (recording["timestamp"] <= saccade_event["end"]),
        "eye1_saccade",
    ] = 1

    if saccade_event["contains_blink"] == 1: #Note here some version is "blink", depends on the item name
        recording.loc[
            (recording["timestamp"] >= saccade_event["start"])
            & (recording["timestamp"] <= saccade_event["end"]),
            "eye1_blink",
        ] = 1

        eye1_x_coordinate  eye1_y_coordinate  eye1_pupil_size  \
0              560.900024         454.100006           1342.0
1              560.599976         454.200012           1341.0
2              560.099976         453.600006           1340.0
3              559.700012         452.899994           1336.0
4              559.500000         452.299988           1332.0
...                   ...                ...              ...
662897                NaN                NaN              NaN
662898                NaN                NaN              NaN
662899                NaN                NaN              NaN
662900                NaN                NaN              NaN
662901                NaN                NaN              NaN

        eye1_pupil_x_coordinate  eye1_pupil_y_coordinate  \
0                         362.0                  -3864.0
1                         359.0                  -3864.0
2                         355.0                  -3869.0
3                         351.0                  -3875.0
4                         349.0                  -3880.0
...                         ...                      ...
662897                 -32768.0                 -32768.0
662898                 -32768.0                 -32768.0
662899                 -32768.0                 -32768.0
662900                 -32768.0                 -32768.0
662901                 -32768.0                 -32768.0

        eye1_href_x_coordinate  eye1_href_y_coordinate  eye1_x_velocity  \
0                       1115.0                  1068.0              NaN
1                       1113.0                  1068.0              NaN
2                       1109.0                  1064.0              NaN
3                       1107.0                  1060.0              NaN
4                       1105.0                  1055.0              NaN
...                        ...                     ...              ...
662897                 -7936.0                 -7936.0              NaN
662898                 -7936.0                 -7936.0              NaN
662899                 -7936.0                 -7936.0              NaN
662900                 -7936.0                 -7936.0              NaN
662901                 -7936.0                 -7936.0              NaN

        eye1_y_velocity  eye1_href_x_velocity  eye1_href_y_velocity  \
0                   NaN                   NaN                   NaN
1                   NaN                   NaN                   NaN
2                   NaN                   NaN                   NaN
3                   NaN                   NaN                   NaN
4                   NaN                   NaN                   NaN
...                 ...                   ...                   ...
662897              NaN                   NaN                   NaN
662898              NaN                   NaN                   NaN
662899              NaN                   NaN                   NaN
662900              NaN                   NaN                   NaN
662901              NaN                   NaN                   NaN

        eye1_raw_x_velocity  eye1_raw_y_velocity  fast_x_velocity  \
0                       NaN                  NaN              0.0
1                       NaN                  NaN              0.0
2                       NaN                  NaN              0.0
3                       NaN                  NaN              0.0
4                       NaN                  NaN              0.0
...                     ...                  ...              ...
662897                  NaN                  NaN              NaN
662898                  NaN                  NaN              NaN
662899                  NaN                  NaN              NaN
662900                  NaN                  NaN              NaN
662901                  NaN                  NaN              NaN

        screen_ppdeg_x_coordinate  screen_ppdeg_y_coordinate  timestamp
0                       38.000000                  38.000000    5315568
1                       38.000000                  38.000000    5315569
2                       38.000000                  38.000000    5315570
3                       38.000000                  38.000000    5315571
4                       38.000000                  38.000000    5315572
...                           ...                        ...        ...
662897                  38.200001                  38.700001    5978465
662898                  38.200001                  38.700001    5978466
662899                  38.200001                  38.700001    5978467
662900                  38.200001                  38.700001    5978468
662901                  38.200001                  38.700001    5978469

[662902 rows x 17 columns]

In [25]:
print(recording)

        eye1_x_coordinate  eye1_y_coordinate  eye1_pupil_size  \
0              560.900024         454.100006           1342.0
1              560.599976         454.200012           1341.0
2              560.099976         453.600006           1340.0
3              559.700012         452.899994           1336.0
4              559.500000         452.299988           1332.0
...                   ...                ...              ...
662897                NaN                NaN              NaN
662898                NaN                NaN              NaN
662899                NaN                NaN              NaN
662900                NaN                NaN              NaN
662901                NaN                NaN              NaN

        eye1_pupil_x_coordinate  eye1_pupil_y_coordinate  \
0                         362.0                  -3864.0
1                         359.0                  -3864.0
2                         355.0                  -3869.0
3                         351.0                  -3875.0
4                         349.0                  -3880.0
...                         ...                      ...
662897                 -32768.0                 -32768.0
662898                 -32768.0                 -32768.0
662899                 -32768.0                 -32768.0
662900                 -32768.0                 -32768.0
662901                 -32768.0                 -32768.0

        eye1_href_x_coordinate  eye1_href_y_coordinate  eye1_x_velocity  \
0                       1115.0                  1068.0              NaN
1                       1113.0                  1068.0              NaN
2                       1109.0                  1064.0              NaN
3                       1107.0                  1060.0              NaN
4                       1105.0                  1055.0              NaN
...                        ...                     ...              ...
662897                 -7936.0                 -7936.0              NaN
662898                 -7936.0                 -7936.0              NaN
662899                 -7936.0                 -7936.0              NaN
662900                 -7936.0                 -7936.0              NaN
662901                 -7936.0                 -7936.0              NaN

        eye1_y_velocity  eye1_href_x_velocity  eye1_href_y_velocity  \
0                   NaN                   NaN                   NaN
1                   NaN                   NaN                   NaN
2                   NaN                   NaN                   NaN
3                   NaN                   NaN                   NaN
4                   NaN                   NaN                   NaN
...                 ...                   ...                   ...
662897              NaN                   NaN                   NaN
662898              NaN                   NaN                   NaN
662899              NaN                   NaN                   NaN
662900              NaN                   NaN                   NaN
662901              NaN                   NaN                   NaN

        eye1_raw_x_velocity  eye1_raw_y_velocity  fast_x_velocity  \
0                       NaN                  NaN              0.0
1                       NaN                  NaN              0.0
2                       NaN                  NaN              0.0
3                       NaN                  NaN              0.0
4                       NaN                  NaN              0.0
...                     ...                  ...              ...
662897                  NaN                  NaN              NaN
662898                  NaN                  NaN              NaN
662899                  NaN                  NaN              NaN
662900                  NaN                  NaN              NaN
662901                  NaN                  NaN              NaN

        screen_ppdeg_x_coordinate  screen_ppdeg_y_coordinate  timestamp  \
0                       38.000000                  38.000000    5315568
1                       38.000000                  38.000000    5315569
2                       38.000000                  38.000000    5315570
3                       38.000000                  38.000000    5315571
4                       38.000000                  38.000000    5315572
...                           ...                        ...        ...
662897                  38.200001                  38.700001    5978465
662898                  38.200001                  38.700001    5978466
662899                  38.200001                  38.700001    5978467
662900                  38.200001                  38.700001    5978468
662901                  38.200001                  38.700001    5978469

        eye1_fixation  eye1_saccade  eye1_blink
0                   0             0           0
1                   0             0           0
2                   0             0           0
3                   0             0           0
4                   0             0           0
...               ...           ...         ...
662897              0             1           1
662898              0             1           1
662899              0             1           1
662900              0             1           1
662901              0             1           1

[662902 rows x 20 columns]

# 5 Write the data into BIDS structure

In [50]:
from copy import deepcopy

metadata['Columns'] = recording.columns.tolist()
print(metadata)
save_metadata = deepcopy(metadata)
# metadata.pop('CalibrationLog', None)
# print(metadata)

{'StopTime': None, 'StartTime': 4359263, 'SamplingFrequency': 1000, 'EyeTrackingMethod': 'P-CR', 'RecordedEye': 'right', 'ScreenAOIDefinition': ['square', [0, 800, 0, 600]], 'PupilFitMethod': 'ellipse', 'PupilFitMethodNumberOfParameters': 5, 'PupilFitParameters': [(1.01, 4.0), (0.15, 0.05), (0.65, 0.65), (0.0, 0.0, 0.3)], 'ValidationPosition': [['eye1', [400, 300]], ['eye1', [400, 51]], ['eye1', [400, 549]], ['eye1', [48, 300]], ['eye1', [752, 300]]], 'ValidationErrors': [('eye1', 0.36, (-6.8, -12.0)), ('eye1', 0.14, (-1.8, -4.8)), ('eye1', 0.27, (-4.7, 9.1)), ('eye1', 0.31, (6.4, -9.8)), ('eye1', 0.3, (7.0, -9.0))], 'PupilThreshold': [79], 'CornealReflectionThreshold': [201], 'LoggedMessages': [(3641144, "ET: Start experiment 'dots'"), (4052547, 'NO Reply is disabled for function eyelink_cal_result'), (4359256, 'ET: start recording'), (4359262, 'RECCFG CR 1000 2 0 R'), (4359262, 'ELCLCFG TOWER'), (4359758, 'ET: stop recording'), (4359759, "ET: Start routine 'dot'"), (4359760, "ET: Start routine 'dot'"), (4359761, "ET: Start routine 'dot'"), (4364752, "ET: Start routine 'dot'"), (4364753, "ET: Start routine 'dot'"), (4364754, "ET: Start routine 'dot'"), (4369752, "ET: Start routine 'dot'"), (4369753, "ET: Start routine 'dot'"), (4374753, "ET: Start routine 'dot'"), (4374754, "ET: Start routine 'dot'"), (4379753, "ET: Start routine 'dot'"), (4379754, "ET: Start routine 'dot'"), (4384753, "ET: Start routine 'dot'"), (4384754, "ET: Start routine 'dot'"), (4384755, "ET: Start routine 'dot'"), (4389753, "ET: Start routine 'dots'"), (4389753, 'ET: dot moved up!'), (4394768, 'ET: dot moved left!'), (4399769, 'ET: dot moved down!'), (4404786, 'ET: dot moved right!'), (4409803, "ET: Start routine 'dots'"), (4409804, 'ET: dot moved left!'), (4414819, 'ET: dot moved right!'), (4419820, 'ET: dot moved up!'), (4424837, 'ET: dot moved down!'), (4429838, "ET: Start routine 'dots'"), (4429838, 'ET: dot moved right!'), (4434853, 'ET: dot moved down!'), (4439854, 'ET: dot moved left!'), (4444870, 'ET: dot moved up!'), (4449871, "ET: Start routine 'dots'"), (4449871, 'ET: dot moved up!'), (4454887, 'ET: dot moved down!'), (4459903, 'ET: dot moved left!'), (4464921, 'ET: dot moved right!'), (4469938, "ET: Start routine 'dots'"), (4469938, 'ET: dot moved up!'), (4474954, 'ET: dot moved right!'), (4479971, 'ET: dot moved down!'), (4484987, 'ET: dot moved left!'), (4490005, "ET: Start routine 'dots'"), (4490006, 'ET: dot moved up!'), (4495021, 'ET: dot moved right!'), (4500021, 'ET: dot moved left!'), (4505038, 'ET: dot moved down!'), (4510056, "ET: Start routine 'dots'"), (4510057, 'ET: dot moved left!'), (4515071, 'ET: dot moved right!'), (4520088, 'ET: dot moved down!'), (4525088, 'ET: dot moved up!'), (4530105, "ET: Start routine 'dots'"), (4530106, 'ET: dot moved up!'), (4535122, 'ET: dot moved left!'), (4540141, 'ET: dot moved right!'), (4545156, 'ET: dot moved down!'), (4550173, "ET: Start routine 'dots'"), (4550173, 'ET: dot moved down!'), (4555189, 'ET: dot moved up!'), (4560205, 'ET: dot moved left!'), (4565206, 'ET: dot moved right!'), (4570223, "ET: Start routine 'dots'"), (4570224, 'ET: dot moved left!'), (4575239, 'ET: dot moved right!'), (4580240, 'ET: dot moved down!'), (4585255, 'ET: dot moved up!'), (4590257, "ET: Start routine 'dots'"), (4590257, 'ET: dot moved up!'), (4595273, 'ET: dot moved down!'), (4600289, 'ET: dot moved right!'), (4605307, 'ET: dot moved left!'), (4610324, "ET: Start routine 'dots'"), (4610324, 'ET: dot moved up!'), (4615340, 'ET: dot moved right!'), (4620341, 'ET: dot moved down!'), (4625358, 'ET: dot moved left!'), (4630375, "ET: Start routine 'dots'"), (4630375, 'ET: dot moved down!'), (4635390, 'ET: dot moved up!'), (4640407, 'ET: dot moved left!'), (4645424, 'ET: dot moved right!'), (4650441, "ET: Start routine 'dots'"), (4650441, 'ET: dot moved right!'), (4655457, 'ET: dot moved left!'), (4660474, 'ET: dot moved up!'), (4665491, 'ET: dot moved down!'), (4670508, "ET: Start routine 'dots'"), (4670508, 'ET: dot moved right!'), (4675524, 'ET: dot moved left!'), (4680541, 'ET: dot moved up!'), (4685558, 'ET: dot moved down!'), (4690575, "ET: Start routine 'dots'"), (4690575, 'ET: dot moved up!'), (4695591, 'ET: dot moved down!'), (4700608, 'ET: dot moved left!'), (4705625, 'ET: dot moved right!'), (4710642, "ET: Start routine 'dots'"), (4710642, 'ET: dot moved right!'), (4715658, 'ET: dot moved left!'), (4720675, 'ET: dot moved up!'), (4725692, 'ET: dot moved down!'), (4730710, "ET: Start routine 'dots'"), (4730710, 'ET: dot moved left!'), (4735725, 'ET: dot moved up!'), (4740726, 'ET: dot moved down!'), (4745742, 'ET: dot moved right!'), (4750760, "ET: Start routine 'dots'"), (4750760, 'ET: dot moved up!'), (4755776, 'ET: dot moved left!'), (4760792, 'ET: dot moved down!'), (4765809, 'ET: dot moved right!'), (4770810, "ET: Start routine 'dots'"), (4770811, 'ET: dot moved down!'), (4775826, 'ET: dot moved up!'), (4780843, 'ET: dot moved right!'), (4785843, 'ET: dot moved left!'), (4790861, "ET: Start routine 'dots'"), (4790861, 'ET: dot moved right!'), (4795877, 'ET: dot moved down!'), (4800893, 'ET: dot moved up!'), (4805910, 'ET: dot moved left!'), (4810928, "ET: Start routine 'dots'"), (4810928, 'ET: dot moved down!'), (4815943, 'ET: dot moved right!'), (4820947, 'ET: dot moved up!'), (4825960, 'ET: dot moved left!'), (4830961, "ET: Start routine 'dots'"), (4830962, 'ET: dot moved up!'), (4835977, 'ET: dot moved right!'), (4840995, 'ET: dot moved down!'), (4846011, 'ET: dot moved left!'), (4851028, "ET: Start routine 'dots'"), (4851028, 'ET: dot moved left!'), (4856044, 'ET: dot moved down!'), (4861045, 'ET: dot moved right!'), (4866061, 'ET: dot moved up!'), (4871063, "ET: Start routine 'dots'"), (4871063, 'ET: dot moved left!'), (4876078, 'ET: dot moved right!'), (4881078, 'ET: dot moved up!'), (4886095, 'ET: dot moved down!'), (4891112, "ET: Start routine 'dots'"), (4891112, 'ET: dot moved up!'), (4896128, 'ET: dot moved down!'), (4901128, 'ET: dot moved right!'), (4906128, 'ET: dot moved left!'), (4911147, "ET: Start routine 'dots'"), (4911147, 'ET: dot moved left!'), (4916162, 'ET: dot moved right!'), (4921162, 'ET: dot moved up!'), (4926179, 'ET: dot moved down!'), (4931180, "ET: Start routine 'dots'"), (4931181, 'ET: dot moved up!'), (4936195, 'ET: dot moved left!'), (4941196, 'ET: dot moved right!'), (4946213, 'ET: dot moved down!'), (4951214, "ET: Start routine 'dots'"), (4951214, 'ET: dot moved left!'), (4956230, 'ET: dot moved down!'), (4961246, 'ET: dot moved up!'), (4966262, 'ET: dot moved right!'), (4971264, "ET: Start routine 'dots'"), (4971264, 'ET: dot moved right!'), (4976280, 'ET: dot moved left!'), (4981280, 'ET: dot moved down!'), (4986296, 'ET: dot moved up!'), (4991315, "ET: Start routine 'dot'"), (4991316, "ET: Start routine 'dot'"), (4991317, "ET: Start routine 'dot'"), (4996315, "ET: Start routine 'dot'"), (4996316, "ET: Start routine 'dot'"), (5001315, "ET: Start routine 'dot'"), (5001316, "ET: Start routine 'dot'"), (5006315, "ET: Start routine 'dot'"), (5006316, "ET: Start routine 'dot'"), (5011314, "ET: Start routine 'dot'"), (5011315, "ET: Start routine 'dot'"), (5016315, "ET: Start routine 'dot'"), (5016316, "ET: Start routine 'dot'"), (5016317, "ET: Start routine 'dot'"), (5021314, "ET: Prepare to start routine 'end'"), (5037282, 'ET: eye tracker stopped')], 'CalibrationCount': np.int64(1), 'CalibrationLog': [(np.int64(3993399), '>>>>>>> CALIBRATION (HV5,P-CR) FOR RIGHT: <<<<<<<<<'), (np.int64(3993400), 'Calibration points:'), (np.int64(3993400), '-34.0, -46.4         0,      0'), (np.int64(3993400), '-32.4, -60.4         0,  -1726'), (np.int64(3993400), '-35.0, -33.0         0,   1726'), (np.int64(3993400), '-54.6, -48.1     -2439,      0'), (np.int64(3993400), '-9.7, -43.7      2439,      0'), (np.int64(3993400), 'eye check box: (L,R,T,B)\n\t  -59    -5   -63   -30'), (np.int64(3993400), 'href cal range: (L,R,T,B)\n\t-3659  3659 -2588  2588'), (np.int64(3993400), 'Cal coeff:(X=a+bx+cy+dxx+eyy,Y=f+gx+goaly+ixx+jyy)\n  -4.5136e-07  109.34  10.19 -0.40774 -0.17415 \n  -3.3852e-07 -12.039  124.87 -0.065453  0.2251'), (np.int64(3993400), 'Prenormalize: offx, offy = -33.998 -46.381'), (np.int64(3993400), 'Gains: cx:81.443 lx:102.494 rx:61.224'), (np.int64(3993400), 'Gains: cy:145.963 ty:132.918 by:147.857'), (np.int64(3993400), 'Resolution (upd) at screen center: X=3.2, Y=1.8'), (np.int64(3993400), 'Gain Change Proportion: X: 0.674 Y: 0.112'), (np.int64(3993400), 'Gain Ratio (Gy/Gx) = 1.792'), (np.int64(3993400), 'Cross-Gain Ratios: X=0.094, Y=0.097'), (np.int64(3993400), 'PCR gain ratio(x,y) = 2.441, 2.177'), (np.int64(3993400), 'CR gain match(x,y) = 1.020, 1.020'), (np.int64(3993400), 'Slip rotation correction OFF'), (np.int64(3993402), 'CALIBRATION HV5 R RIGHT   GOOD'), (np.int64(4000379), 'VALIDATION HV5 R RIGHT GOOD ERROR 0.31 avg. 0.36 max  OFFSET 0.22 deg. -2.5,-7.8 pix.')], 'CalibrationType': 'HV5', 'AverageCalibrationError': [0.31], 'MaximalCalibrationError': [0.36], 'CalibrationResultQuality': ['GOOD'], 'CalibrationResultOffset': [0.22, (-2.5, -7.8)], 'CalibrationResultOffsetUnits': ['deg', 'pixels'], 'Columns': ['eye1_x_coordinate', 'eye1_y_coordinate', 'eye1_pupil_size', 'eye1_pupil_x_coordinate', 'eye1_pupil_y_coordinate', 'eye1_href_x_coordinate', 'eye1_href_y_coordinate', 'eye1_x_velocity', 'eye1_y_velocity', 'eye1_href_x_velocity', 'eye1_href_y_velocity', 'eye1_raw_x_velocity', 'eye1_raw_y_velocity', 'fast_x_velocity', 'screen_ppdeg_x_coordinate', 'screen_ppdeg_y_coordinate', 'timestamp', 'eye1_fixation', 'eye1_saccade', 'eye1_blink']}

In [51]:
metadata = save_metadata

In [52]:
def convert_to_int(metadata):
    if 'CalibrationCount' in metadata:
        metadata['CalibrationCount'] = int(metadata['CalibrationCount']) if isinstance(metadata['CalibrationCount'], (np.int32, np.int64, int)) else metadata['CalibrationCount']
    if "CalibrationLog" in metadata:
        metadata["CalibrationLog"] = [(int(x[0]),x[1]) if isinstance(x[0], (np.int32, np.int64, int)) else x for x in metadata['CalibrationLog']]
    return metadata
  
convert_metadata = convert_to_int(metadata)
# print(convert_metadata)

In [53]:
# Load the autoreload extension
%load_ext autoreload
# Set autoreload to update the modules every time before executing a new line of code
%autoreload 2

import importlib
from write_bids_yiwei import write_bids_from_df
out_dir = DATA_PATH
edf_extension = 'EDF'
edf_name = edf_name
filename = edf_name.split('.')[0]
print(f'bid filename: {filename}')

write_bids_from_df(
    recording, convert_metadata,
    out_dir,
    filename,
)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
bid filename: 015_mreyetrack_4points_2026-03-04_19h27

('/home/debi/jaime/repos/MR-EyeTrack/data/study/sub-015/et/015_mreyetrack_4points_2026-03-04_19h27.tsv.gz',
 '/home/debi/jaime/repos/MR-EyeTrack/data/study/sub-015/et/015_mreyetrack_4points_2026-03-04_19h27.json')

Now the files are generated.
- EDF Path
    - \<filename\>.EDF
    - \<filename\>.tsv.gz

In [54]:
print(recording)

        eye1_x_coordinate  eye1_y_coordinate  eye1_pupil_size  \
0              594.200012         142.100006           2165.0
1              594.299988         142.000000           2162.0
2              594.599976         142.199997           2158.0
3              594.599976         141.300003           2158.0
4              594.599976         140.000000           2160.0
...                   ...                ...              ...
663046         430.700012         318.200012           1698.0
663047         430.299988         318.299988           1698.0
663048         430.000000         316.899994           1699.0
663049         430.100006         315.399994           1699.0
663050         430.500000         314.799988           1697.0

        eye1_pupil_x_coordinate  eye1_pupil_y_coordinate  \
0                       -2524.0                  -6726.0
1                       -2523.0                  -6726.0
2                       -2521.0                  -6725.0
3                       -2520.0                  -6731.0
4                       -2518.0                  -6740.0
...                         ...                      ...
663046                  -4017.0                  -5648.0
663047                  -4021.0                  -5648.0
663048                  -4023.0                  -5658.0
663049                  -4021.0                  -5668.0
663050                  -4017.0                  -5672.0

        eye1_href_x_coordinate  eye1_href_y_coordinate  eye1_x_velocity  \
0                       1346.0                 -1093.0              NaN
1                       1346.0                 -1094.0              NaN
2                       1348.0                 -1093.0              NaN
3                       1349.0                 -1099.0              NaN
4                       1348.0                 -1108.0              NaN
...                        ...                     ...              ...
663046                   213.0                   126.0              NaN
663047                   210.0                   126.0              NaN
663048                   207.0                   117.0              NaN
663049                   208.0                   107.0              NaN
663050                   211.0                   103.0              NaN

        eye1_y_velocity  eye1_href_x_velocity  eye1_href_y_velocity  \
0                   NaN                   NaN                   NaN
1                   NaN                   NaN                   NaN
2                   NaN                   NaN                   NaN
3                   NaN                   NaN                   NaN
4                   NaN                   NaN                   NaN
...                 ...                   ...                   ...
663046              NaN                   NaN                   NaN
663047              NaN                   NaN                   NaN
663048              NaN                   NaN                   NaN
663049              NaN                   NaN                   NaN
663050              NaN                   NaN                   NaN

        eye1_raw_x_velocity  eye1_raw_y_velocity  fast_x_velocity  \
0                       NaN                  NaN              0.0
1                       NaN                  NaN              0.0
2                       NaN                  NaN              0.0
3                       NaN                  NaN              0.0
4                       NaN                  NaN              0.0
...                     ...                  ...              ...
663046                  NaN                  NaN          -5669.0
663047                  NaN                  NaN          -5669.0
663048                  NaN                  NaN          -5669.0
663049                  NaN                  NaN          -5669.0
663050                  NaN                  NaN          -5669.0

        screen_ppdeg_x_coordinate  screen_ppdeg_y_coordinate  timestamp  \
0                       38.099998                  38.099998    4359263
1                       38.099998                  38.099998    4359264
2                       38.099998                  38.099998    4359265
3                       38.099998                  38.099998    4359266
4                       38.099998                  38.099998    4359267
...                           ...                        ...        ...
663046                  37.700001                  37.700001    5022309
663047                  37.700001                  37.700001    5022310
663048                  37.700001                  37.700001    5022311
663049                  37.700001                  37.700001    5022312
663050                  37.700001                  37.700001    5022313

        eye1_fixation  eye1_saccade  eye1_blink
0                   0             0           0
1                   0             0           0
2                   0             0           0
3                   0             0           0
4                   0             0           0
...               ...           ...         ...
663046              1             0           0
663047              1             0           0
663048              1             0           0
663049              1             0           0
663050              0             0           0

[663051 rows x 20 columns]